#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PencilsDown.Resource", IsApplication=true)]

namespace PencilsDown
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int late = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int officialLogo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pencil = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int relax = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int skull = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int target = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int working = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int wrap = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int youtube = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int button1 = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int editText1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int editText2 = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int imageView1 = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int imageView2 = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int inputs = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int top = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int demo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
